[project]
name = "case-study"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "earthengine-api>=1.7.43",
    "folium>=0.20.0",
    "geopandas>=1.1.4",
    "ipykernel>=7.3.0",
    "mapclassify>=2.11.0",
    "matplotlib>=3.11.1",
    "pandas>=3.0.5",
]

[project.scripts]
case-study = "case_study:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "markdown>=3.10.3",
]
